### ISSUE TITLE
Create a database of places

### ISSUE THREAD

**Issue by romanova2** [ucsb-cs56-webapps/ucsb-cs56-go#8]
1. Create a places class 2. Create a places model (ie list of places to encapsulate places) 3. create a database of places (using mongoDB)

**Comment by pconrad** [comment]
THIS IS JUST AN EXAMPLE.. NOT A REAL COMMENT..

If this were real, it might Nuan, the mentor for this team writing:

Approved, Estimate: 200

**Comment by nuankw** [comment]
Approved, Estimate: 400
